/*
 * This source file was generated by the Gradle 'init' task
 */
package _MicroservicioComand;

public class Library {
    public static void main(String[] args) {
        System.out.println("hola");
    }
}

